### ISSUE TITLE
[question] Should we replace links with depends_on in docker-compose configs?

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1091]
It's stated [here, in Step two — removing links](https://medium.com/@giorgioto/docker-compose-yml-from-v1-to-v2-3c0f8bb7a48e#.uj9y6325k) that since `version: 2` of docker-compose, `links` section can be dropped safely in favour of `depends_on`. 

Yet, not only we've been using both `links` and `depends_on` in our configs so far, but also those sections' contents differ, e.g.
```yaml
depends_on:
    - postgres
links:
    - postgres
    - mailhog
``` 
in `dev.yml` -- was this made for a reason?
