### ISSUE TITLE
Add circle CI testing in the template

### ISSUE THREAD

**Issue by rlaverde** [pydanny/cookiecutter-django#1331]
I'll be nice to could select circleCI (http://circleci.com/) as the CI service of the template
```
$ cookiecutter https://github.com/pydanny/cookiecutter-django
...

Select Continuum integration service:
1 - Travis CI
2 - CircleCI
Choose from 1, 2 [1]: 1
```

And seleting 2 will generate a `circle.yml ` with a basic configuration

If this feature is approved I could provide a PR with the change.

**Comment by webyneter** [comment]
@rlaverde I don't mind this initiative, however we should bear in mind maintenance cost for the feature. @pydanny, @jayfk, @luzfcb what do you think?

**Comment by jayfk** [comment]
If one of the core devs is actively using CircleCI and is happy keeping it up-to-date, sure.

**Comment by luzfcb** [comment]
@webyneter I do not use circleci in any of my projects.

**Comment by pydanny** [comment]
I do not use circleci either.

If no core dev uses it but @circleci wants to have their service in this project, they can assign a staff member to provide ongoing support. If they do so, then we'll accept a PR for it. Otherwise, we can't add to our maintenance burden.

**Comment by webyneter** [comment]
I don't use Circle CI either. Agreed to @pydanny, maintanance burden might turn out to be too heavy for us.

**Comment by sfdye** [comment]
I'm actively using Circle CI with cookie cutter-django. Would be happy help with this.

**Comment by pydanny** [comment]
@sfdye Thank you for the offer, but from experience, we really need vendor support from @circleci itself.

**Comment by sfdye** [comment]
@pydanny Sure, understood 😄

**Comment by pydanny** [comment]
Since @circleci hasn't responded, I'm closing this issue. We'll reopen if we hear from them.

**Comment by timmyomahony** [comment]
@sfdye would you be able to share your config for a circle build with a cookiecutter project here? I'm currently trying to set it up.

**Comment by sfdye** [comment]
@timmyomahony here you go, sample CircleCi config with codecov support.

```
version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.5.4
        environment:
          DATABASE_URL: YOUR_DATABASE_URL
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            py.test --cov=./
            codecov --token=token
      - store_artifacts:
          path: test-reports/
          destination: tr1
```
