### ISSUE TITLE
celery services exit with status code 2 on docker compose setup (from master)

### ISSUE THREAD

**Issue by jsmedmar** [pydanny/cookiecutter-django#1588]
* **Im submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

🐛

* **What is the current behavior?**

celery services exit with status code 2 on docker compose setup (from master)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

Generate project from master:

![screen shot 2018-03-28 at 10 52 10 am](https://user-images.githubusercontent.com/8843150/38037102-24687c46-3276-11e8-8e86-b900da85068b.png)

Then run:

    docker-compose -f local.yml build
    docker-compose -f local.yml up

Got these errors:

    celerybeat_1    | /entrypoint.sh: line 13: POSTGRES_USER: parameter not set
    celeryworker_1  | /entrypoint.sh: line 13: POSTGRES_USER: parameter not set
    api_celerybeat_1 exited with code 2
    api_celeryworker_1 exited with code 2

* **Please tell us about your environment:**

Using docker, so I guess this shouldn't be a problem?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Full log just in case:

![screen shot 2018-03-28 at 10 58 09 am](https://user-images.githubusercontent.com/8843150/38037470-f2799bf6-3276-11e8-93d0-3c999c2e0d45.png)

**Comment by webyneter** [comment]
@jsmedmar seems like the problem is that celery containers are missing envs from `.envs/.local/.django` and `.envs/.local/.postgres` files -- try to alter `celeryworker` and `celerybeat` from `local.yml` as follows and restart:

```yaml
celeryworker:
    <<: *django
    depends_on:
     - postgres
     - redis
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.production/.celery
    command: /start-celeryworker.sh

  celerybeat:
    <<: *django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.production/.celery
    command: /start-celerybeat.sh
```
