### ISSUE TITLE
Add pgAdmin4 when using docker

### ISSUE THREAD

**Issue by imcatta** [pydanny/cookiecutter-django#1732]
## Description
Ask the users if they want to add [pgAdmin4](https://www.pgadmin.org/) as a service in the local.yml file if they choose to use docker 

## Rationale
pgAdmin can be a usefull tool to use during the development to see what's inside the database.

**Comment by vladdoster** [comment]
Is the shell not enough? Django gives you command in mange.py to get a dbshell!

**Comment by browniebroke** [comment]
I'm personally not super interested in adding this to the project, I haven't found much need for it so far. 

Unless other maintainers are happy to looks after upgrades, documentation and potential issues, I'm afraid we'll have to reject this feature idea.

Out of curiosity, how hard is it to add to a generated project @imcatta? If it's only a matter of adding a service in `local.yaml` and connecting the ports, maybe we can leave it to interested users to edit their configs?

**Comment by sfdye** [comment]
When it comes to pg client, people's preference differ. I wouldn't want to add this to the project.

**Comment by imcatta** [comment]
Ok, got your points. @browniebroke you're right, it only takes a few lines in `local.yml` to add pgAdmin to a generated project.
I'm closing the issue

**Comment by xjlin0** [comment]
Like this? (copied from https://lucacorbucci.medium.com/how-to-run-postgresql-and-pgadmin-using-docker-57c500018a96)
```yaml
version: "3"
services:

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    restart: unless-stopped
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
```
