### ISSUE TITLE
How to setup Caddy DNS challenge for dynamic subdomains

### ISSUE THREAD

**Issue by srserx** [pydanny/cookiecutter-django#1812]
CONTEXT
----------
I've correctly deployed my Django app to Digital Ocean using a single domain in Caddy --> mywebsite.com

Now, I've got to support multiple subdomains, because I am using django-tenants (https://github.com/tomturner/django-tenants) (domains are created dynamically, there's not a predefined set of subdomains). 

**So I've changed my domain in the Caddyfile to --> .mywebsite.com**

If now I try to deploy my app again, I get a Caddy error which says that for wildcard domains, DNS Challenge needs to be set up. 
For this purpose, I add, as mentioned in the Caddy website (https://caddyserver.com/docs/automatic-https#dns-challenge), the DNS challenge configuration for Digital Ocean.

My current Caddyfile looks like this:

```
{$DOMAIN_NAME} {

    tls {
       dns digitalocean
    }

    proxy / django:5000 {
        header_upstream Host {host}
        header_upstream X-Real-IP {remote}
        header_upstream X-Forwarded-Proto {scheme}
    }

    log stdout
    errors stdout
    gzip
}
```

And I've set up the environment variable with the digital ocean token.

PROBLEM
----------
When I try to deploy the app again, Caddy throws a new error which says that "digitalocean" dns provider is not supported. But really it's in the official documentation.

I think I have to add the desired provider someway, like suggested in: https://github.com/dodekeract/cloudflocaddy/blob/master/docker-compose.yml 

```
version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_caddy: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: autocheck_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: autocheck_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  caddy:
    build:
      args:
         plugins: digitalocean   <------- ADDED THIS!
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    image: autocheck_production_caddy
    depends_on:
      - django
    volumes:
      - production_caddy:/root/.caddy
    env_file:
      - ./.envs/.production/.caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:3.2
```

But still I get the error. I've been struggling with this for 3 days, but I've had no luck so far.

Does someone have any suggestions on how to get the DNS Challenge working?

Thank you in advance!
