### ISSUE TITLE
Project created with Celery does not configure environment variables correctly

### ISSUE THREAD

**Issue by axsaucedo** [pydanny/cookiecutter-django#2413]
## What happened?

When project gets created with Celery and run with Docker, it fails with multiple errors due not having the POSTGRES and REDIS environment variables set correctly in the env file.

The errors are initially "column django_celery_beat_periodictask.clocked_id does not exist". This gets fixed by adding the POSTGRES variables. 

The next error is "/entrypoint: line 10: REDIS_URL: unbound variable" which is fixed if the REDIS_URL is added manually.

I had to add the "env_file" section to the local.yml to make it work:
```
  celerybeat:
    <<: *django
    image: seldon_klaw_local_celerybeat
    depends_on:
      - redis
      - postgres
      
    ports: []
    command: /start-celerybeat
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
```

## What should've happened instead?

The env variables and docker config should be configured such that there are no errors on startup

## Steps to reproduce

Install with following steps:

```
You've downloaded /home/alejandro/.cookiecutters/cookiecutter-django before. Is it okay to delete and re-download it? [yes]:
project_name [My Awesome Project]: Seldon KLAW
project_slug [seldon_klaw]:
description [Behold My Awesome Project!]: Seldon Cluster Manager
author_name [Daniel Roy Greenfeld]: Alejandro Saucedo
domain_name [example.com]: seldon.io
email [alejandro-saucedo@example.com]: as@seldon.io
version [0.1.0]: 0.0.1
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]: 4
timezone [UTC]:
windows [n]:
use_pycharm [n]:
use_docker [n]: y
Select postgresql_version:
1 - 11.3
2 - 10.8
3 - 9.6
4 - 9.5
5 - 9.4
Choose from 1, 2, 3, 4, 5 [1]:
Select js_task_runner:
1 - None
2 - Gulp
Choose from 1, 2 [1]:
Select cloud_provider:
1 - AWS
2 - GCP
3 - None
Choose from 1, 2, 3 [1]: 3
custom_bootstrap_compilation [n]:
use_compressor [n]:
use_celery [n]: y
use_mailhog [n]:
use_sentry [n]:
use_whitenoise [n]: y
use_heroku [n]:
Select ci_tool:
1 - None
2 - Travis
3 - Gitlab
Choose from 1, 2, 3 [1]:
keep_local_envs_in_vcs [y]:
debug [n]:
 [WARNING]: You chose not to use a cloud provider, media files won't be served in production.
 [SUCCESS]: Project initialized, keep up the good work!
```

Then run docker-compose local.yml.
