### ISSUE TITLE
Add cache for Docker-Based Projects in CI

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pydanny/cookiecutter-django#2588]
## Description

CI takes a really long time to build the docker containers. Approximately 4 minutes on just building with so many requirements. Although CI like Travis in their docs say they don't support caching since each build is always provisioned on a new machine, we can take advantage of GitHub packages to push docker images there using GH actions.

An example is detailed here: https://testdriven.io/blog/faster-ci-builds-with-docker-cache/

The other option would be to rewrite a bit of config/settings/test.py and rewrite the CI configuration files to run __without__ Docker and instead just "install" and run tests like a normal project.

## Rationale

CI takes a really long time to build for Docker projects.

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

Faster docker builds during CI or, in general, faster CI runs. Plus, less whining.

**Comment by Andrew-Chen-Wang** [comment]
Hm so it seems doable. Run the pip install on local.txt, then use Docker to start celery, if available. It’ll cut down a large chunk of time since I believe 1/3 of the time is spent installing the python packages, so using the built in Travis cache will help.

**Comment by Andrew-Chen-Wang** [comment]
@browniebroke Would this allow for a decrease in the number of docker images generated, too? I’m not quite acquainted with this celery multi start functionality, albeit already implemented in my Travis config, and I even think the “worker1 worker2” part is not needed, only needing for the worker and beat part.

Currently, there are 3 docker images that take up 1GB each by default if celery is used since the compose file utilizes anchors. Perhaps using these multi start commands could eliminate the need for these anchors? I guess the problem, which I haven’t tested yet, is the logging...

**Comment by arnav13081994** [comment]
@Andrew-Chen-Wang I have experimented with using cache for github actions. And it seems the best (and easiest) solution to decrease the time regardless of the CI tool used would be to use a docker image registry like dockerhub or github container image registry. This, however, would require one to add the following to the `build` directive of compose services in both `local.yml` and `production.yml`

Example:

**Original**:

```
services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

```

**Proposed**:


```
services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      **cache_from:
        - [COOKIECUTTER_DOCKERHUB_REPO OR COOKIECUTTER_GITHUBREGISTRY_REPO]:[IMAGE_TAG_OR_NAME]**
    image: {{ cookiecutter.project_slug }}_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

```

And then we would need to add a corresponding step to login to the chosen registry on all CI tools before the step that executes `docker-compose  build`.

The reason why this reduces the time is because before the images are built docker compose will first check the image registry to see what all image layers can be re-used to build the same image. This is because of `cache_from` which defaults to the local image registry (if not set) and will use the cache manifest from the specified registry to re-build only from the `"busted"` layers.

Also in the current avatar of the compose files, there is only 1 image built for `django`, `celeryworker`,  `celerybeat`, and `flower`. If you run `docker image ls`, all 4 images will have the same ID. The 4 entries is just docker's way of saying that the same image is being referenced in more than 1 ` 'repository' `

Another option would be to use the `docker buildx build` to build django and delegate building other images to compose. This would not require any changes to the compose file. The build command however would either need to `cache-from` and `cache-to` the registry or the local CI tool cache.
