### ISSUE TITLE
How to run command /start in django service production.yml in Dockerrun.aws..json?

### ISSUE THREAD

**Issue by vincegnzls** [pydanny/cookiecutter-django#2765]
I am trying to deploy the Docker setup of this project in AWS Elastic Beanstalk. I am trying to convert the command: /start into Dockerrun.aws.json, but I'm not sure if it's the correct conversion since the task doesn't run properly inside the ECS container.  I replaced traefik with my custom nginx Dockerfile and when I run this with docker-compose locally using the production.yml file, they work fine (I can access the admin site of Django), but when I start to deploy them in Elastic Beanstalk, the django task stops, and the nginx runs with no problem. I am also using AWS ECR to upload my images after building. I suspect that it might be the command /start that is causing the problem but I am not sure. I would appreciate it if anyone can help me.

 Please refer below for the config files:

Please note that I have removed some configuration such as environment variables and postgres service. The environment variables are placed in the Elastic Beanstalk application and for the postgres, I am using the RDS database in AWS. The Dockerfile for Django is also not changed, it is from the generated Dockerfile of the project.

**production.yml**:

```
version: "3"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: <id>.dkr.ecr.ap-southeast-1.amazonaws.com/django-docker
    command: /start

  nginx:
    build: ./compose/production/nginx/
    image: <id>.dkr.ecr.ap-southeast-1.amazonaws.com/django-docker-nginx
    depends_on:
      - django
    ports:
      - 80:80
```

**Dockerrun.aws.json**:

```
{
    "AWSEBDockerrunVersion": 2,
    "containerDefinitions": [
        {
            "command": [
                "/start"
            ],
            "image": "<id>.dkr.ecr.ap-southeast-1.amazonaws.com/django-docker",
            "name": "django",
            "hostname": "django",
            "memory": 256,
            "essential": false
        },
        {
            "image": "<id>.dkr.ecr.ap-southeast-1.amazonaws.com/django-docker-nginx",
            "name": "nginx",
            "dependsOn": [
                {
                    "condition": "START",
                    "containerName": "django"
                }
            ],
            "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 80
                }
            ],
            "essential": true,
            "links": [
                "django"
            ],
            "memory": 128
        }
    ]
}
```
