### ISSUE TITLE
traefik_1: Unable to obtain ACME certificate

### ISSUE THREAD

**Issue by julialoh** [pydanny/cookiecutter-django#2766]
## What happened?
I'm attempting to deploy on a docker. I've run the build command, but reach an error when I run the up command. I get: 
```
traefik_1       | time="2020-08-25T20:52:19Z" level=error msg="Unable to obtain ACME certificate for domains \"cmw.com\": unable to generate a certificate for the domains [cmw.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=letsencrypt.acme rule="Host(`cmw.com`)" routerName=flower-secure-router
traefik_1       | time="2020-08-25T20:52:19Z" level=error msg="Unable to obtain ACME certificate for domains \"cmw.com,www.cmw.com\": unable to generate a certificate for the domains [cmw.com www.cmw.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=letsencrypt.acme routerName=web-secure-router rule="Host(`cmw.com`) || Host(`www.cmw.com`)"
```

## What should've happened instead?
I believe that traefik_1 should've completed and I could deploy on the docker. 

## Steps to reproduce

I ran: docker-compose -f production.yml build
And then: docker-compose -f production.yml up 

Here is my production.yml: 
```
version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cmw_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cmw_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: cmw_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: cmw_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: cmw_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: cmw_production_flower
    command: /start-flower
```

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by foarsitter** [comment]
To me the error message is crystal clear: 
```
Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/
```
With a bit of luck you will succeed today in the first try.

**Comment by julialoh** [comment]
It didn't work :( It's the same error.

**Comment by julialoh** [comment]
Am I supposed to do something besides jus run the build and up command?

**Comment by browniebroke** [comment]
Have you read [the documentation page](https://cookiecutter-django.readthedocs.io/en/latest/deployment-with-docker.html) for this? There is a section about HTTPS, which is describes the requirements:

> The Traefik reverse proxy used in the default configuration will get you a valid certificate from Lets Encrypt and update it automatically. All you need to do to enable this is to make sure that your DNS records are pointing to the server Traefik runs on.

A simple way to do so is to create a A record pointing to the IP of your server or load balancer leading to it. This part is dependent on your hosting provider so you might want to chek with them.

You might also want to check [the articles section in the readme](https://github.com/pydanny/cookiecutter-django#articles).

In case this is not clear, to obtain a TLS certificate, the server running your production stack needs to publicly accessible on the internet. This won't work on your dev machine (at least not without configuring your home router).

**Comment by martibosch** [comment]
Hello,

I encountered the same issue, which I posted [in the Traefik forums](https://community.traefik.io/t/unable-to-obtain-acme-certificate-for-domains-with-cookiecutter-django-and-porkbun/11227). As you can see in the link, adding a non-TLS router solved the issue in my case.

Best,
Martí

**Comment by gjae** [comment]
> Hello,
> 
> I encountered the same issue, which I posted [in the Traefik forums](https://community.traefik.io/t/unable-to-obtain-acme-certificate-for-domains-with-cookiecutter-django-and-porkbun/11227). As you can see in the link, adding a non-TLS router solved the issue in my case.
> 
> Best, Martí

Good day! Did you had to remove the section  ?
```yaml
    http:
      redirections:
        entryPoint:
          to: web-secure
```
I have the same issue right now
