### ISSUE TITLE
Local Docker: failed connection to the database

### ISSUE THREAD

**Issue by julialoh** [pydanny/cookiecutter-django#2767]
## What happened?
I'm trying to run locally in my docker, but get this error when I run the up command: 
```  connection = Database.connect(**conn_params)
django          |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
django          |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django          | psycopg2.OperationalError: could not connect to server: Connection refused
django          | 	Is the server running on host "localhost" (127.0.0.1) and accepting
django          | 	TCP/IP connections on port 5432?
django          | could not connect to server: Cannot assign requested address
django          | 	Is the server running on host "localhost" (::1) and accepting
django          | 	TCP/IP connections on port 5432?
django          | 
django          | 
django          | The above exception was the direct cause of the following exception:
django          | 
django          | Traceback (most recent call last):
django          |   File "manage.py", line 31, in <module>
django          |     execute_from_command_line(sys.argv)
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
django          |     utility.execute()
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
django          |     self.fetch_command(subcommand).run_from_argv(self.argv)
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
django          |     self.execute(*args, **cmd_options)
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
django          |     output = self.handle(*args, **options)
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
django          |     res = handle_func(*args, **kwargs)
django          |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 86, in handle
django          |     executor = MigrationExecutor(connection, self.migration_progress_callback)
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
django          |     self.loader = MigrationLoader(self.connection)
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
django          |     self.build_graph()
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
django          |     self.applied_migrations = recorder.applied_migrations()
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
django          |     if self.has_table():
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
django          |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
django          |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
django          |     return func(*args, **kwargs)
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
django          |     return self._cursor()
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 236, in _cursor
django          |     self.ensure_connection()
django          |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
django          |     return func(*args, **kwargs)
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
django          |     self.connect()
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
django          |     raise dj_exc_value.with_traceback(traceback) from exc_value
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
django          |     self.connect()
django          |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
django          |     return func(*args, **kwargs)
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
django          |     self.connection = self.get_new_connection(conn_params)
django          |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
django          |     return func(*args, **kwargs)
django          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
django          |     connection = Database.connect(**conn_params)
django          |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
django          |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django          | django.db.utils.OperationalError: could not connect to server: Connection refused
django          | 	Is the server running on host "localhost" (127.0.0.1) and accepting
django          | 	TCP/IP connections on port 5432?
django          | could not connect to server: Cannot assign requested address
django          | 	Is the server running on host "localhost" (::1) and accepting
django          | 	TCP/IP connections on port 5432?
django          | 
django exited with code 1
```

## What should've happened instead?
Django should've finished, allowing me to access my work locally from my docker. 

## Steps to reproduce
I ran: docker-compose -f local.yml build 
and then: docker-compose -f local.yml up 

My local.yml looks like: 
```
version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cmw_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cmw_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: cmw_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs
      - ./config:/app/config
      - ./cmw:/app/cmw
    ports:
      - "7000:7000"

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *django
    image: cmw_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: cmw_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: cmw_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower
```
and my database settings in base.py looks like: 
```
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "cmw",
        "USER": "postgres",
        "PASSWORD": "new_password", 
        "HOST": "localhost",
        "PORT": "5432",
    }
}
DATABASES["default"]["ATOMIC_REQUESTS"] = True
```

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)
