### ISSUE TITLE
Control Django migrations and Collecstatic run through compose env vars

### ISSUE THREAD

**Issue by arnav13081994** [pydanny/cookiecutter-django#2806]
## Description

What are you proposing? How should it be implemented?

I propose adding 2 env vars to docker-compose -  `DJANGO_RUN_MIGRATIONS` and `DJANGO_RUN_COLLECSTATIC` -  for controlling whether migrations and collectstatic should be run on Django Service startup. 

The `/start` script can look for the value of those 2 vars and then decide whether migrate and/or collectstatic need to be run. 

## Rationale

Why should this feature be implemented?

 The current setup (through the `/start` BASH script) runs migrate and collecstatic every time a container is started, which is rather unnecessary. And since it's copied in the Dockerfile, any change to that behaviour involves rebuilding the image. By implementing this change docker-compose will become more user friendly, intuitive and will make it easier and faster to run migrations and collecstatic on demand.

**Comment by Andrew-Chen-Wang** [comment]
At least for me, when I'm running compose in production.yml, I'll run migrate and collectstatic regardless since **I'm most likely on a single server setup** with CI/CD (hence having Traefik). This really wouldn't be the case for multi server setup since they wouldn't be using docker-compose anymore.

My only issue with this is that, what if you forget? If you do, then you'll get 500 errors since you forgot to migrate (due to failing rows or you'll have incorrect data in your table). New JS files? Forgot about those too. That's my only issue with this.

**Comment by foarsitter** [comment]
The [local](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/start) bash script is running migrate, the [production](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/start) version runs collectstatic. 

In my opinion, this way is how it should be. When deploying to a clustered environment your migrations needs to backwards compatible so you can perform a rolling update. Before replacing my containers I run a one-off container with `python manage.py migrate`. The old containers are now running on the new database migration. After that I replace the containers with the new version. 

Each container needs the `staticfiles` so it does not make much sense to start without `collectstatic`.

To solve the issue of forgetfulness is scripting: create a simple bash script that does your deploy. First create a backup, push to s3, pull the new image, run the migrations in a one-off, etc.

**Comment by arnav13081994** [comment]
@Andrew-Chen-Wang I agree with you regarding 1 server setup but compose can also be used for multi-node setups as well. I, for example, am using docker-compose (via docker stack deploy) with docker swarm. I have no idea about other orchestrators though so I'll take your word for it. Regarding 500 errors, the 2 vars can both default to `true` and can be easily changed via docker-compose and for extra safety can be present as `true` in the `.env/.base` env_file as well. Eg:



```
  django: &django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        BUILD_ENV: ${BUILD_ENV}
    image: trainerratings_${BUILD_ENV}_django:1.0
    env_file:
      - ./docker/.env/.base/
      - ./docker/.env/.${BUILD_ENV}
    # Vars specified here will override vars in env_file.
    environment:
      - DJANGO_RUN_MIGRATIONS=true
      - DJANGO_RUN_COLLECSTATIC=true
    command: /start
    networks:
      - frontend
      - backend

```


@foarsitter I didn't think about the case of static files being served from Django itself. You're right about that.  
Also regarding your one-off container point, you could still do that with this and you could also run collectstatic in another one-off container (or with the same one by chaining the 2) and for all other containers, the 2 vars could be set to false which would really speed up all the other containers coming online. That actually sounds like a win win situation to me, if I do understand your point correctly. Also, even using CollectFast with collecstatic can take 10 or more seconds, which is something that can totally be avoided by all other containers and will further aid 0 downtime.
