### ISSUE TITLE
Why is a separate Dockerfile necessary for Traefik

### ISSUE THREAD

**Issue by arnav13081994** [pydanny/cookiecutter-django#2822]
I am not able to understand the reason why a custom traefik Docerfile is being used.

The static and dynamic config files can be mounted as `ro` Read-Only in the container and `acme.json` file is something that traefik creates on its own, so creating and setting `0600` permissions also seem unnecessary.

The whole file seems unnecessary to me. Am I missing something?

**Comment by demestav** [comment]
What alternative do you suggest?

**Comment by arnav13081994** [comment]
@demestav 

Docker-compose can just have this for **traefik service**:

```
  traefik:
    image: traefik:v2.2.11
    depends_on:
      - django
    volumes:
      - ./docker/traefik/production/traefik.yml:/etc/traefik/traefik.yml:ro
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      {%- if cookiecutter.use_celery == 'y' %}
      - "0.0.0.0:5555:5555"
      {%- endif %}

```
