### ISSUE TITLE
PyCharm Configurations & Docker problem.

### ISSUE THREAD

**Issue by banksee** [pydanny/cookiecutter-django#984]
Hello guys! I'm having a problems with getting to work PyCharm configurations for docker-composer.
Here is what I get when trying to run Docker Migrate from PyCharm configurations:
![screenshot from 2017-01-08 00-31-47](https://cloud.githubusercontent.com/assets/4748206/21745702/e09df648-d539-11e6-84a1-2dc6e42cd020.png)

I am not able to start the test as well:
![screenshot from 2017-01-08 00-33-06](https://cloud.githubusercontent.com/assets/4748206/21745712/12735b72-d53a-11e6-8d2e-de0f36395ff1.png)

I am using default dev.yml config for docker-composer:
``` yaml
version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=budger

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=budger
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - mailhog

  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=budger
    volumes:
      - .:/app
    links:
      - postgres



  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
```

Here is my interpreter settings (according to [this doc](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docs/pycharm/configuration.rst)):
![screenshot from 2017-01-08 00-42-20](https://cloud.githubusercontent.com/assets/4748206/21745768/7d49c020-d53b-11e6-83c6-8fc9940ac17f.png)
![screenshot from 2017-01-08 00-42-44](https://cloud.githubusercontent.com/assets/4748206/21745770/7d553536-d53b-11e6-87df-2f5a2a385ac1.png)
![screenshot from 2017-01-08 00-43-09](https://cloud.githubusercontent.com/assets/4748206/21745769/7d524330-d53b-11e6-990f-4f7516147085.png)

PyCharm version: 2016.3
OS: Ubuntu 16.04

I would really appreciate any help! Thanks!
